config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :visitor
  root 'visitor#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  validates :email, presence:true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/showcase_controller.rb
class ShowcaseController < ApplicationController
    def index
      @slideshow_images_names = ['dog1', 'dog2', 'dog3']
      @slideshow_selected_image_index = 1
    end
end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  def index
    @visitor = Visitor.new
  end

  def new
    @visitor = Visitor.new
  end
  
  def create
    @visitor = Visitor.new(first_name: visitor_params[:first_name], last_name: visitor_params[:last_name], phone_number: visitor_params[:phone_number], email: visitor_params[:email], message: visitor_params[:message])
   if @visitor.save
    flash[:success] = "Message envoyé !"
   else
    flash[:danger] = "Message non remis (un/des champ(s) n'ont pas été complétés)"
   end
   redirect_to root_path(anchor: 'tips')
  end

  def visitor_params
    params.require(:visitor).permit(:first_name,:last_name,:phone_number,:email,:message)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/showcase_helper.rb
module ShowcaseHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>emma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visitor/_flash.html.erb
<% if flash[:danger] %>
<div class="alert_n">
<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>

  <p><%= flash[:danger]%></p>
</div>
<% end %>

<% if flash[:success] %>
<div class="alert_y">
<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>

  <p><%= flash[:success]%></p>
</div>
<% end %>

app/views/visitor/_form.html.erb
<section id="cover">
    <div id="cover-caption">
        <div id="container1" class="container">
                    <h1 class="display-10">DEMANDE DE CONTACT</h1>
                    <div class="info-form">
                        <%= form_for @visitor, url: visitor_index_path, html: {action: :post, class: "form-signin mt-3" } do |f| %>
                            <div class="form-group">
                            <%= f.text_field :email, autocomplete: "email", placeholder: "Adresse email", class: "form-control" %>
                            </div>
                            <div class="actions mt-5">
                            <%= submit_tag "Valider", :class => 'w-100 btn btn-primary'  %>
                          </div>
                       <% end %>
            </div>
        </div>
    </div>
</section>

app/views/visitor/_jumbotron1.html.erb
<div class="jumbotron jumboindex py-2">
    <div class="logowrap">
      <img class="img-responsive" width="130px" height="" src="<%= asset_path( 'logo.svg' ) %>">
    </div>
    <section id="cover">
    <div class="row">
    <div class="container column" id="titlepage">
    <h2> Une application qui gère AUTOMATIQUEMENT </br> la paperasse de vos proches en perte d'autonomie </h2></div>
        <div class="container column">
        <div id="cover-caption">
        <div class="formcontainer">
        <div class="titleform">
              <h1 class="display-10">Informations</h1>
              </div>
              </br> Entrez votre adresse mail pour recevoir toutes les infos concernant la sortie de l'outil d'aide administrative emma
              <div class="info-form">
                  <%= form_for @visitor, url: visitor_index_path, html: {action: :post, class: "form-signin mt-3" } do |f| %>
                      <div class="form-group">
                      <%= f.text_field :email, autocomplete: "email", placeholder: "Adresse email", class: "form-control" %>
                      </div>
                      <div class="actions mt-5">
                      <%= submit_tag "Valider", :class => 'btn btn-info btn-lg btn-block'  %>
                    </div>
                  <% end %>
            </div>
            </div>
                    </div>
                
      </div>
    </section>
  </p>
</div>

app/views/visitor/_page.html.erb
<div class="section" id="intersection">
<h1>Pour vos proches en perte d'autonomie</h1></br> 
<p class="lead text-center">
Emma vous aide à vous recentrer sur l'essentiel 
</p>
</div>


<div id="section2">


  
  
  
  
  
<div class="container" id="section1">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="page-header text-center">
      <h1>Votre assistant administratif personnalisé</h1>
    </div>
    
    <p class="lead text-center">
      Emma est une application qui vous permet de mieux gérer la paperasse de vos proches en perte d'autonomie. Emma centralise vos demandes et les envoit AUTOMATIQUEMENT après avoir entré les données 1 SEULE fois
    </p>
    </br></br></br>
    <div class="page-header text-center">
      <h1>et plus encore...</h1>
    </div>
    <p class="lead text-center">
      Emma permet également de résoudre les problemes clients de vos proches en vous proposant des solutions qui VOUS arrangent </br> <strong>&</strong>
  </p>

  </div>
</div>
<div class="container4">
<img style='height: 100%; width: 100%; object-fit: contain' src="<%= asset_path( 'emma.png' ) %>"></div>

</div>

app/views/visitor/index.html.erb
<%= render 'jumbotron1' %>
<%= render 'page' %>
<a id="tips"></a>
<%= render 'flash'%>
<%= yield %>
<%= render 'footer' %>